# Generated by Django 5.0.9 on 2024-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField(verbose_name='YYYY-MM-DD HH:MM:ss')),
                ('value', models.IntegerField()),
            ],
        ),
    ]
